spring:
  application:
    name: devcards-service

  datasource:
    url: jdbc:postgresql://localhost:5432/devcards_db
    username: postgres
    password: postgres

    jpa:
      hibernate:
        ddl-auto: validate

    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml

    server:
      port: 8080