INSERT INTO public.flashcards(
	front_text, back_text, image_url, study_day, deleted)
	VALUES ('User sees infinite loading spinner. What is the FIRST thing you would inspect?', 'Open browser Network tab and check whether the HTTP request is pending, failed, or completed.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTtE_Uk1ZOFp9_lT5akQi9h2L8WRFPA2kMf_710Rqg0g&s=10', 'MONDAY', false),
	('Users API returns data succesfully but UI still shows 0 users. What is the most likely issue?', 'Signal value is never updated with the API response.', 'https://i.postimg.cc/BZDpgd0Q/Screenshot-2026-06-20-153347.png', 'MONDAY', false),
	('The request reaches backend but returns 401. What area whould you investigate first?', 'Authentication and JWT token handling.', 'https://i.postimg.cc/8cFqKwNY/Screenshot-2026-06-20-154002.png', 'MONDAY', false),
	('What is the most likely cause?', 'The user object is undefined or not loaded yet.', 'https://i.postimg.cc/pX5BT4sC/Screenshot-2026-06-20-160331.png', 'MONDAY', false),
	('A new Angular version has been released. As a developer, what would you investigate BEFORE upgrading your project?', 'Breaking changes, migration guide, dependency compatability, and benefits relevant to your project.', 'https://i.postimg.cc/L5wGrWTv/Screenshot-2026-06-20-161432.png', 'MONDAY', false),
	('As a developer, what is the most important question to ask about this announcement?', 'What specific tasks become faster or cheaper, and what risks or limitations remain?', 'https://i.postimg.cc/kGQhp525/Screenshot-2026-06-20-161819.png', 'MONDAY', false),
	('The HTTP request is never sent. Where would you start debugging?', 'Verify that the click handler is executed and that the service method is actually called.', 'https://i.postimg.cc/C10G6KY1/Screenshot-2026-06-20-154644.png', 'TUESDAY', false),
	('The page is partially broken. Which request is the most likely root cause?', 'GET /permissions because it returns 500 Internal Server Error.', 'https://i.postimg.cc/Xv4qRBZt/Screenshot-2026-06-20-155034.png', 'TUESDAY', false),
	('API returns data successfully. What should you inspect next?', 'Verify that the component assings the response data to the variable used by the template.', 'https://i.postimg.cc/cCR4ksxy/Screenshot-2026-06-20-155544.png', 'TUESDAY', false),
	('User clicks Save but nothing happens. What should you verify first?', 'Confirm that save() method exists and is executed when the button is clicked.', 'https://i.postimg.cc/Sx3F9B4K/Screenshot-2026-06-20-155937.png', 'TUESDAY', false),
	('Which layer appears to be failing?', 'Backend API or database lookup for user 15.', 'https://i.postimg.cc/c4fDx61V/Screenshot-2026-06-20-160610.png', 'TUESDAY', false),
	('Your application becomes unavailable during a cloud outage. What software engineering lesson should you learn from this event?', 'External dependencies can fail. Design system with resilience, monitoring, and recovery strategies.', 'https://i.postimg.cc/vBkssD8V/Screenshot-2026-06-20-161523.png', 'TUESDAY', false),
	('Should you immediately migrate your production system because of this news?', 'No. First evaluate whether the improvements solve a real problem for your use case.', 'https://i.postimg.cc/26pGNDRy/Screenshot-2026-06-20-162027.png', 'TUESDAY', false);
